Move version check early

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -7,7 +7,19 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
-      - name: Cache NPM dependencies
+      - name: Get version
+        id: get_version
+        run: |
+          VERSION=$(node -p "require('./package.json').version")
+          echo "version=$VERSION" >> $GITHUB_OUTPUT
+      - name: Fail if tag already exists
+        run: |
+          VERSION=${{ steps.get_version.outputs.version }}
+          if git ls-remote --tags origin "refs/tags/v$VERSION" | grep -q .; then
+            echo "::error title=Release Tag Exists::Tag v$VERSION already exists. Increment version and try again."
+            exit 1
+          fi
+      - name: Setup NPM cache
         uses: actions/cache@v4
         with:
           path: ~/.npm
@@ -20,15 +32,3 @@ jobs:
         run: npm install --global platform-os-tool --no-audit --no-fund
       - name: Package with OS tool
         run: os package-tool . --no-increment-version
-      - name: Get version from package.json
-        id: get_version
-        run: |
-          VERSION=$(node -p "require('./package.json').version")
-          echo "version=$VERSION" >> $GITHUB_OUTPUT
-      - name: Fail if tag already exists
-        run: |
-          VERSION=${{ steps.get_version.outputs.version }}
-          if git ls-remote --tags origin "refs/tags/v$VERSION" | grep -q .; then
-            echo "::error title=Release Tag Exists::Tag v$VERSION already exists. Increment version and try again."
-            exit 1
-          fi
